
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 08 17:53:01 CST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPRELACIONAL = 39;
  public static final int ARRAYTOK = 12;
  public static final int WHENTOK = 42;
  public static final int THENTOK = 33;
  public static final int PUTTOK = 2;
  public static final int COMATOK = 7;
  public static final int OPBOOL = 40;
  public static final int INTEGERTOK = 25;
  public static final int TYPETOK = 24;
  public static final int BOOLEANTOK = 26;
  public static final int OPSUMA = 37;
  public static final int ENDLINE = 5;
  public static final int RANGETOK = 31;
  public static final int IFTOK = 32;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int BOOLEANVALUE = 8;
  public static final int error = 1;
  public static final int NUMBER = 44;
  public static final int INOUTTOK = 16;
  public static final int ASIGNATION = 10;
  public static final int RETURNTOK = 18;
  public static final int ELSETOK = 36;
  public static final int OUTTOK = 15;
  public static final int LETTER = 13;
  public static final int BEGINTOK = 21;
  public static final int INTOK = 14;
  public static final int EXITTOK = 41;
  public static final int ISTOK = 20;
  public static final int FUNCIONTOK = 17;
  public static final int OFTOK = 19;
  public static final int FLOATTOK = 27;
  public static final int UNDERSCORE = 43;
  public static final int FORTOK = 30;
  public static final int ENDTOK = 22;
  public static final int PROCEDURETOK = 23;
  public static final int ELSIFTOK = 35;
  public static final int LOOPTOK = 29;
  public static final int WHILETOK = 28;
  public static final int PARDER = 4;
  public static final int GETTOK = 6;
  public static final int OPMULT = 38;
  public static final int POINTTOK = 9;
  public static final int ANOTATION = 11;
  public static final int IDENTIFIER = 34;
}

